# 숫자 연산

In [2]:
a=7

In [3]:
b=5

In [4]:
z=a+b 
print (z)
    #z


12


In [5]:
z = a+b 
z
x = a-b 
x
c = a*b 
c
v = a/b 
v
    zz = a//b 
    zz
        xx = a%b 
        xx

IndentationError: unexpected indent (Temp/ipykernel_27444/2749109727.py, line 9)

In [6]:
print("+"."->",z)
print("-","->",x)
print("*","->",c)
print("/","->".v)
print("//","->",zz)
print("%","->",xx)

SyntaxError: invalid syntax (Temp/ipykernel_27444/218191138.py, line 1)

# list 연산

In [7]:
lst = [1,2,3]
lst

[1, 2, 3]

In [8]:
print(lst)

[1, 2, 3]


In [9]:
print(lst*3) #* : 반복연산

[1, 2, 3, 1, 2, 3, 1, 2, 3]


In [10]:
print(lst+3) #출력에러

TypeError: can only concatenate list (not "int") to list

# 리스트자료 -> 배열변환자료

## 리스트

In [11]:
lst= [1,2,3]
lst

[1, 2, 3]

In [12]:
print(lst*2)

[1, 2, 3, 1, 2, 3]


# 배열 변환

# import numpy as np

In [13]:
import numpy as np

In [14]:
a_lst = np.array(lst) #리스트자료 배열 변환
a_lst

array([1, 2, 3])

In [15]:
print(a_lst*2)

[2 4 6]


In [16]:
print(a_lst+100)

[101 102 103]


In [17]:
print(a_lst-1)

[0 1 2]


# arange()

In [18]:
a= np.arange(12) # 배열 lsit, 시작 명시하지 않으면 0부터(시작,종료,단계)
#(12) 0에서 시작 n-1 인덱스까지 인덱스 : 항상 0부터 시작
#(2,12) 2~n-1
#(0,12,2) 0~n-1까지 2단계
# array(), list[] -> array([])
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [19]:
c = np.arange(1,12,2)
c

array([ 1,  3,  5,  7,  9, 11])

In [20]:
d = a.reshape(4,3) #기존 데이터는 유지하고 차원과 형상을 바꾸는데 사용(행,열) 0의 자료#reshape 행렬
d

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [21]:
data= np.arange(12).reshape(4,3) ## .은 그 안을 의미한다.
data

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [22]:
data = np.arange(12).reshape(4,3)
data[data<=4]=0 # 4이하인 값을 다 0으로 바꿔준다
data

array([[ 0,  0,  0],
       [ 0,  0,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [23]:
k= np.arange(12).reshape(3,4)
k

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [24]:
k.max() #전체 최고값 # 변수.max

11

In [25]:
k.mean() #전체 평균

5.5

# axis = 0 or 1 : 방향

In [26]:
k.sum(axis=0) #x축 기준 각열의 합계

array([12, 15, 18, 21])

In [27]:
k

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [28]:
k[0,0] #변수명[인덱스 행번호, 인덱스 열번호] 3 주의 ㅔ-130, dataframe어쩌구 못적음

0

In [29]:
k[0,3]

3

In [30]:
k[2,3]

11

In [31]:
k

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [32]:
k[0]

array([0, 1, 2, 3])

In [33]:
k[1]

array([4, 5, 6, 7])

In [34]:
k[1:] #[n:]] n인덱스 행부터 이후

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [35]:
k[0:2,1:3] # 행0~1까지 열1~2까지 조합

array([[1, 2],
       [5, 6]])

# 난수생성(np.random 모듈)

## np.random.random()


In [36]:
import random

In [37]:
#0부터 1사이의 랜덤 실수를 리턴, random float x, 0.0<=x<1.0
random_a=np.random.random()
print(random_a)

0.8550830239972407


# np.random.rand()

In [38]:
# 0과 1사이의 값에서 난수 어레이를 생성
rand_a = np.random.rand()
rand_b = np.random.rand(5)
rand_c = np.random.rand(2,3)

print(rand_a)
print("*"*70)

print(rand_b)
print("*"*70)

print(rand_c)

0.7953557969312832
**********************************************************************
[0.92572724 0.75461157 0.97624314 0.39760292 0.36604289]
**********************************************************************
[[0.79147372 0.50690095 0.95562612]
 [0.36033942 0.66521429 0.57692506]]


# np.random.randn()


In [39]:
#-1에서 1 사이 표준 정규분포(standard normal disrtibution)으로 부터 난수 값을 반환

randn_a = np.random.randn()
print(randn_a)
print("*"*70)

randn_b = np.random.randn(5) #5개
print(randn_b)
print("*"*70)

randn_c = np.random.randn(100) #100개
print(randn_c)
print("*"*70)

randn_d = np.random.randn(2,3) #2행 3열
print(randn_d)

-0.4234178488329431
**********************************************************************
[-1.98923057  1.12625914  0.60410467 -0.81660724 -0.33917159]
**********************************************************************
[-0.34827937 -0.62825091 -0.19394837  1.87101229 -0.74081918 -0.18757776
  0.35603802  0.80320846 -0.82039277  0.58095298 -0.58182756 -0.64947994
 -0.93988661 -1.04224024 -1.57263705  0.61680392 -0.30385805 -0.65257245
 -0.78579115  0.67109427 -1.01359224  0.67333436 -0.06636152  0.55659619
  0.16124079  0.57724239  0.98288551 -0.39383063  0.32433382  0.66708134
 -1.39705032 -1.27415466 -0.73912134  0.53756521 -2.14929931 -0.97853665
 -1.15229601 -0.39310815  0.21020941 -1.06714318 -1.56923695  1.48369528
  1.9261422   0.12189171  0.03515356 -0.37892938  0.36238946  0.12690352
  0.07449075  0.29001083 -0.87316774 -1.46152012  0.79810607  0.71424436
  0.85827812 -0.5451902  -0.0806376  -0.19204823 -0.45677597 -2.56779254
  0.40803323 -0.47360424  0.31348991 -0.562941

In [40]:
# (a,b,size) a~b-1 범위에서 임의의 "정수"를 만듬, a를 생략하면 0부터 시작
randint_a = np.random randint(2,size=5)  # (최소값,최대값,size) -> 최소값~최대값)
print(randint_a)
print("*"*70)

randint_b = np.random randint(2,3,size=7)  #size 2를 7개 
print(randint_b)
print("*"*70)

SyntaxError: invalid syntax (Temp/ipykernel_27444/2329679180.py, line 2)

# np.random.normal(a,b,c)

In [42]:
#np.random.normal(0,1,1000) #[정규분표] 평균 0, 표준편차 1, 개수 1000개
x_normal = np.random.normal(0,1,1000)
print(x_normal)

[-1.41378014e+00  5.32516016e-01 -1.73572904e+00 -2.77176806e-01
 -7.01651771e-02 -1.08100205e+00 -1.98638854e+00  7.27453848e-01
  5.31255382e-01 -1.00559107e+00 -1.36085210e+00  1.69244055e+00
  5.22250400e-02 -2.37755175e-01  2.31316022e+00 -1.32854038e+00
 -1.81115008e+00  1.70346056e+00  1.49361474e+00 -4.09758895e-02
 -1.45839787e-01  9.70627031e-01  4.62072240e-01 -3.51028640e-01
 -1.56815176e+00  1.59906120e+00  5.66450259e-01 -3.44172691e-01
  1.64362027e+00  2.85328631e-01  5.73857065e-01  2.18495693e+00
  6.92289415e-01  7.46518429e-01 -2.44372967e-01  8.52715341e-02
  8.67279812e-01 -8.52074622e-01 -5.86246013e-01  1.26317032e+00
  5.59306693e-01  4.23549532e-01  4.57397751e-01  2.16756886e+00
  1.21711984e+00 -1.18371721e+00  2.44345553e-01  9.23913691e-02
  2.48914585e-01  1.63579334e-01  6.21520563e-01  3.20547982e-01
 -7.22051679e-01  7.14069877e-01 -1.25683204e+00  1.50971739e+00
  1.75442709e+00 -4.84923734e-01  4.12333444e-01 -2.45775587e-01
 -2.04519351e+00 -2.51382

# np.random.uniform(0,1,1000)

In [43]:
# random.uniform 함수는 인자로 들어온 a,b사이의 c개 실수(float)를 반환
# uniform 함수의 랜덤 범위는 a<=x <=b
x_uniform =np.random.uniform(0,1,1000)
print(x_uniform)

[1.83643370e-01 5.39524929e-01 1.77548666e-01 9.63622973e-01
 3.08016977e-01 5.69573767e-01 2.02384550e-01 6.65049053e-01
 8.30180270e-01 7.59050073e-01 9.52744496e-01 8.15934495e-01
 5.07408226e-01 6.36195229e-01 6.88081236e-01 6.82771981e-01
 7.05196935e-01 5.78779334e-01 7.44252795e-02 2.74572701e-01
 9.31652520e-01 2.92975979e-01 6.54010835e-01 8.15054946e-01
 7.07091707e-01 1.68185588e-01 7.38367514e-01 8.95557545e-01
 9.45780945e-01 9.32590110e-01 7.14711624e-01 3.79342479e-01
 9.09596002e-02 3.11731216e-01 3.41168596e-01 6.94713381e-01
 6.45595253e-01 8.64504186e-01 6.35248366e-02 8.06618412e-01
 6.64468265e-01 7.85849501e-01 7.24318561e-01 4.74718212e-01
 1.66530991e-01 8.06575552e-01 3.47527483e-01 3.58075310e-01
 1.78132783e-01 7.41606150e-01 9.14315688e-02 8.19960072e-01
 9.18424850e-01 8.75255629e-01 8.28298560e-01 1.68641075e-02
 9.70264283e-01 1.94131637e-01 8.90191065e-01 3.65742906e-02
 9.60217976e-01 7.34307535e-02 3.22724667e-01 4.79042849e-01
 7.24154489e-01 6.630917

# numpy 배열결합 -> p287
 - np.vstack
 - np/hstack
 - np.concatenate

In [44]:
ar1 = np.arange(4).reshape(2,2)
ar2= np.arange(3,7).reshape(2,2)

In [45]:
ar1

array([[0, 1],
       [2, 3]])

In [46]:
ar2

array([[3, 4],
       [5, 6]])

# np.vstack, np.concatenate([ar1,ar2],axis=0: 1행,2행으로 세로 합치기

In [48]:
df_vstack=np.vstack([ar1,ar2]): df_vstack #행 기준 합치기

SyntaxError: invalid syntax (Temp/ipykernel_27444/1076746124.py, line 1)

In [49]:
df_hstack=np.hstack([ar1,ar2]) :df_hstack #열기준 합치기

SyntaxError: invalid syntax (Temp/ipykernel_27444/446526251.py, line 1)